/* ============================================
   ARKNETCH — Product Database & Data Layer
   ============================================ */

const CATEGORIES = [
  { id: 'electronics', name: 'Electronics', icon: '📱', count: 6 },
  { id: 'fashion', name: 'Fashion', icon: '👗', count: 6 },
  { id: 'home', name: 'Home & Kitchen', icon: '🏠', count: 5 },
  { id: 'books', name: 'Books', icon: '📚', count: 4 },
  { id: 'sports', name: 'Sports', icon: '⚽', count: 4 },
  { id: 'beauty', name: 'Beauty', icon: '💄', count: 3 },
  { id: 'toys', name: 'Toys & Games', icon: '🎮', count: 3 },
  { id: 'grocery', name: 'Groceries', icon: '🛒', count: 3 },
  { id: 'health', name: 'Health', icon: '💊', count: 3 },
  { id: 'automotive', name: 'Automotive', icon: '🚗', count: 2 }
];

const BRANDS = ['Arknetch','TechVista','StyleCraft','HomeLux','FitPro','GreenLeaf','BookWorm','PlayZone','AutoPrime','BeautyGlow'];

const PRODUCTS = [
  // ELECTRONICS
  {id:1,name:'Arknetch Pro Max Smartphone',slug:'arknetch-pro-max',category:'electronics',brand:'Arknetch',
    price:69999,originalPrice:89999,discount:22,rating:4.6,reviewCount:12453,
    image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop','https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop'],
    description:'Experience the future with the Arknetch Pro Max. Featuring a stunning 6.8" AMOLED display, 200MP camera system, and the most powerful AI chip ever made.',
    features:['6.8" Super AMOLED 120Hz Display','200MP Triple Camera System','Snapdragon 8 Gen 4 Processor','5500mAh Battery with 120W Fast Charging','12GB RAM + 256GB Storage','IP68 Water & Dust Resistant'],
    specs:{'Display':'6.8" AMOLED','Processor':'Snapdragon 8 Gen 4','RAM':'12GB','Storage':'256GB','Battery':'5500mAh','Camera':'200MP + 50MP + 12MP'},
    colors:['#1a1a2e','#c0c0c0','#7c3aed','#10b981'],inStock:true,stockCount:145,seller:'Arknetch Official',deliveryDays:1,freeDelivery:true,tags:['smartphone','5g','flagship','camera']},
  {id:2,name:'Arknetch UltraBook Pro 16"',slug:'arknetch-ultrabook',category:'electronics',brand:'Arknetch',
    price:94999,originalPrice:119999,discount:21,rating:4.8,reviewCount:6721,
    image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop','https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=600&fit=crop'],
    description:'The ultimate creative powerhouse. 16" 4K Retina display, M4 Pro chip, 32GB unified memory, and 20-hour battery life.',
    features:['16" 4K Retina Display','M4 Pro Chip','32GB Unified Memory','1TB SSD Storage','20-Hour Battery Life','Thunderbolt 5 Ports'],
    specs:{'Display':'16" 4K Retina','Processor':'M4 Pro','RAM':'32GB','Storage':'1TB SSD','Battery':'20 hours','Weight':'1.8kg'},
    colors:['#1a1a2e','#c0c0c0'],inStock:true,stockCount:89,seller:'Arknetch Official',deliveryDays:2,freeDelivery:true,tags:['laptop','ultrabook','professional']},
  {id:3,name:'Arknetch AirPods Ultra',slug:'arknetch-airpods',category:'electronics',brand:'Arknetch',
    price:24999,originalPrice:29999,discount:17,rating:4.5,reviewCount:8932,
    image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop'],
    description:'Supreme noise cancellation meets perfect sound. 40-hour battery, spatial audio, and seamless connectivity.',
    features:['Active Noise Cancellation','Spatial Audio with Head Tracking','40-Hour Battery Life','IPX5 Water Resistant','Wireless Charging Case','Multi-Device Connectivity'],
    specs:{'Type':'Over-ear','Driver':'50mm','ANC':'Hybrid Active','Battery':'40 hours','Connectivity':'Bluetooth 5.3','Weight':'250g'},
    colors:['#1a1a2e','#f8fafc','#7c3aed'],inStock:true,stockCount:234,seller:'Arknetch Official',deliveryDays:1,freeDelivery:true,tags:['headphones','audio','anc','wireless']},
  {id:4,name:'TechVista 4K Smart TV 55"',slug:'techvista-smarttv',category:'electronics',brand:'TechVista',
    price:44999,originalPrice:64999,discount:31,rating:4.4,reviewCount:3421,
    image:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=600&fit=crop'],
    description:'Immerse yourself in cinematic brilliance with 55" QLED 4K display, Dolby Vision, and built-in streaming.',
    features:['55" QLED 4K Display','Dolby Vision & Atmos','120Hz Refresh Rate','Built-in Smart OS','Voice Control','4 HDMI 2.1 Ports'],
    specs:{'Display':'55" QLED 4K','HDR':'Dolby Vision','Refresh Rate':'120Hz','Speakers':'40W Dolby Atmos','Ports':'4x HDMI 2.1','Smart OS':'ArknetchOS'},
    colors:[],inStock:true,stockCount:67,seller:'TechVista Store',deliveryDays:3,freeDelivery:true,tags:['tv','4k','smart','entertainment']},
  {id:5,name:'Arknetch Smart Watch Ultra',slug:'arknetch-watch',category:'electronics',brand:'Arknetch',
    price:34999,originalPrice:44999,discount:22,rating:4.7,reviewCount:5643,
    image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop'],
    description:'Your ultimate health companion. Advanced health sensors, GPS, 72-hour battery, and 100m water resistance.',
    features:['1.9" Always-On AMOLED','Blood Oxygen & ECG Monitoring','Built-in GPS & Compass','72-Hour Battery Life','100m Water Resistant','500+ Workout Modes'],
    specs:{'Display':'1.9" AMOLED','Sensors':'SpO2, ECG, Temp','GPS':'Dual-band','Battery':'72 hours','Water':'100m','Storage':'32GB'},
    colors:['#1a1a2e','#c0c0c0','#f59e0b'],inStock:true,stockCount:178,seller:'Arknetch Official',deliveryDays:1,freeDelivery:true,tags:['smartwatch','fitness','health']},
  {id:6,name:'TechVista DSLR Pro Camera',slug:'techvista-dslr',category:'electronics',brand:'TechVista',
    price:59999,originalPrice:74999,discount:20,rating:4.6,reviewCount:2187,
    image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop'],
    description:'Professional-grade 45MP full-frame mirrorless camera with 8K video recording and in-body stabilization.',
    features:['45MP Full-Frame Sensor','8K Video Recording','5-Axis In-Body Stabilization','693 AF Points','Dual Card Slots','Weather Sealed Body'],
    specs:{'Sensor':'45MP Full-Frame','Video':'8K 30fps','ISO':'100-51200','AF Points':'693','Stabilization':'5-Axis IBIS','Weight':'580g'},
    colors:['#1a1a2e'],inStock:true,stockCount:45,seller:'TechVista Store',deliveryDays:2,freeDelivery:true,tags:['camera','photography','professional']},

  // FASHION
  {id:7,name:'Premium Italian Leather Jacket',slug:'leather-jacket',category:'fashion',brand:'StyleCraft',
    price:4999,originalPrice:8999,discount:44,rating:4.3,reviewCount:1876,
    image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop'],
    description:'Handcrafted genuine Italian leather jacket with premium YKK zippers and quilted lining for ultimate style.',
    features:['100% Genuine Italian Leather','Premium YKK Zippers','Quilted Satin Lining','Multiple Pockets','Adjustable Waist Belt','Lifetime Warranty'],
    specs:{'Material':'Italian Leather','Lining':'Quilted Satin','Closure':'YKK Zipper','Care':'Leather conditioner'},
    colors:['#1a1a2e','#8B4513','#800020'],sizes:['S','M','L','XL','XXL'],inStock:true,stockCount:89,seller:'StyleCraft Fashion',deliveryDays:3,freeDelivery:true,tags:['jacket','leather','fashion','men']},
  {id:8,name:'Elegant Silk Evening Dress',slug:'silk-dress',category:'fashion',brand:'StyleCraft',
    price:3499,originalPrice:5999,discount:42,rating:4.5,reviewCount:2341,
    image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=600&fit=crop'],
    description:'Stunning silk evening dress with hand-embroidered details and flowing silhouette for special occasions.',
    features:['100% Pure Silk','Hand-Embroidered Details','Flowing A-Line Silhouette','Hidden Side Zipper','Fully Lined','Dry Clean Only'],
    specs:{'Material':'Pure Silk','Style':'A-Line','Length':'Full','Care':'Dry Clean'},
    colors:['#1a1a2e','#800020','#1e3a5f','#10b981'],sizes:['XS','S','M','L','XL'],inStock:true,stockCount:56,seller:'StyleCraft Fashion',deliveryDays:4,freeDelivery:true,tags:['dress','silk','evening','women']},
  {id:9,name:'FitPro Running Shoes X1',slug:'running-shoes',category:'fashion',brand:'FitPro',
    price:6999,originalPrice:9999,discount:30,rating:4.7,reviewCount:5621,
    image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop'],
    description:'Engineered for performance with carbon fiber plate, responsive foam, and breathable knit upper.',
    features:['Carbon Fiber Speed Plate','Energy-Return Foam Midsole','Breathable Knit Upper','Rubber Outsole','Reflective Details','Lightweight 245g'],
    specs:{'Upper':'Engineered Knit','Midsole':'ZoomX Foam','Outsole':'Rubber','Weight':'245g','Drop':'8mm'},
    colors:['#ef4444','#1a1a2e','#06b6d4','#f59e0b'],sizes:['7','8','9','10','11','12'],inStock:true,stockCount:312,seller:'FitPro Sports',deliveryDays:2,freeDelivery:true,tags:['shoes','running','sports','fitness']},
  {id:10,name:'Luxury Chronograph Watch',slug:'chronograph-watch',category:'fashion',brand:'StyleCraft',
    price:12999,originalPrice:19999,discount:35,rating:4.6,reviewCount:1932,
    image:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&h=600&fit=crop'],
    description:'Swiss-inspired chronograph with sapphire crystal glass, Japanese movement, and genuine leather strap.',
    features:['Japanese Quartz Movement','Sapphire Crystal Glass','Genuine Leather Strap','100m Water Resistant','Chronograph Function','Luminous Hands'],
    specs:{'Movement':'Japanese Quartz','Crystal':'Sapphire','Case':'42mm SS','Water':'100m','Strap':'Genuine Leather'},
    colors:['#c0c0c0','#f59e0b','#1a1a2e'],inStock:true,stockCount:67,seller:'StyleCraft Fashion',deliveryDays:2,freeDelivery:true,tags:['watch','luxury','chronograph','accessories']},
  {id:11,name:'Polarized Aviator Sunglasses',slug:'aviator-sunglasses',category:'fashion',brand:'StyleCraft',
    price:2499,originalPrice:3999,discount:38,rating:4.4,reviewCount:3456,
    image:'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop'],
    description:'Classic aviator design with polarized UV400 lenses, titanium frame, and spring hinges.',
    features:['Polarized UV400 Lenses','Titanium Frame','Spring Hinges','Anti-Scratch Coating','Premium Case Included','Lifetime Frame Warranty'],
    specs:{'Lens':'Polarized UV400','Frame':'Titanium','Style':'Aviator','Weight':'28g'},
    colors:['#f59e0b','#1a1a2e','#06b6d4'],inStock:true,stockCount:189,seller:'StyleCraft Fashion',deliveryDays:2,freeDelivery:true,tags:['sunglasses','aviator','polarized','uv']},
  {id:12,name:'Classic Stretch Denim Jeans',slug:'denim-jeans',category:'fashion',brand:'StyleCraft',
    price:1999,originalPrice:3499,discount:43,rating:4.3,reviewCount:7892,
    image:'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=600&fit=crop'],
    description:'Premium stretch denim with a perfect slim fit, made from sustainable organic cotton blend.',
    features:['Organic Cotton Blend','2% Elastane Stretch','Slim Fit','Reinforced Stitching','5-Pocket Design','Machine Washable'],
    specs:{'Material':'98% Organic Cotton, 2% Elastane','Fit':'Slim','Rise':'Mid','Care':'Machine Wash'},
    colors:['#1e3a5f','#1a1a2e','#6b7280'],sizes:['28','30','32','34','36','38'],inStock:true,stockCount:445,seller:'StyleCraft Fashion',deliveryDays:2,freeDelivery:true,tags:['jeans','denim','casual','men']},

  // HOME & KITCHEN
  {id:13,name:'Smart HEPA Air Purifier',slug:'air-purifier',category:'home',brand:'HomeLux',
    price:14999,originalPrice:21999,discount:32,rating:4.5,reviewCount:2345,
    image:'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop'],
    description:'Medical-grade HEPA purifier covering 600 sq ft. Smart sensors auto-adjust fan speed based on air quality.',
    features:['H13 HEPA Filter','Covers 600 sq ft','Smart Air Quality Sensor','Auto/Sleep/Turbo Modes','App & Voice Control','Ultra-Quiet 22dB'],
    specs:{'Filter':'H13 HEPA + Carbon','Coverage':'600 sq ft','Noise':'22-55dB','CADR':'400 m³/h','Control':'App + Voice'},
    colors:['#f8fafc','#1a1a2e'],inStock:true,stockCount:78,seller:'HomeLux Living',deliveryDays:3,freeDelivery:true,tags:['air purifier','health','smart home']},
  {id:14,name:'Robot Vacuum & Mop Combo',slug:'robot-vacuum',category:'home',brand:'HomeLux',
    price:19999,originalPrice:29999,discount:33,rating:4.6,reviewCount:4567,
    image:'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop'],
    description:'LiDAR navigation robot vacuum with simultaneous mopping, auto-empty dock, and smart mapping.',
    features:['LiDAR Navigation','5000Pa Suction Power','Auto-Empty Dock','Simultaneous Vacuum & Mop','Smart Room Mapping','180-Min Battery'],
    specs:{'Suction':'5000Pa','Battery':'180 min','Dust Bin':'400ml','Water Tank':'300ml','Noise':'65dB'},
    colors:[],inStock:true,stockCount:56,seller:'HomeLux Living',deliveryDays:3,freeDelivery:true,tags:['robot vacuum','smart home','cleaning']},
  {id:15,name:'Professional Espresso Machine',slug:'espresso-machine',category:'home',brand:'HomeLux',
    price:24999,originalPrice:34999,discount:29,rating:4.8,reviewCount:1876,
    image:'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&h=600&fit=crop'],
    description:'Barista-quality espresso at home. 20-bar pressure, built-in grinder, steam wand, and touch display.',
    features:['20-Bar Italian Pump','Built-in Conical Burr Grinder','Professional Steam Wand','Touch LCD Display','PID Temperature Control','Auto-Cleaning'],
    specs:{'Pressure':'20 bar','Grinder':'Conical Burr','Water Tank':'2.5L','Warming':'Dual Cup Warmer','Display':'Touch LCD'},
    colors:['#c0c0c0','#1a1a2e'],inStock:true,stockCount:34,seller:'HomeLux Living',deliveryDays:4,freeDelivery:true,tags:['coffee','espresso','kitchen','appliance']},
  {id:16,name:'Orthopedic Memory Foam Mattress',slug:'memory-mattress',category:'home',brand:'HomeLux',
    price:29999,originalPrice:49999,discount:40,rating:4.7,reviewCount:3245,
    image:'https://images.unsplash.com/photo-1631049035182-249067d7618e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1631049035182-249067d7618e?w=600&h=600&fit=crop'],
    description:'12-inch luxury memory foam mattress with cooling gel layer and zero motion transfer technology.',
    features:['12-inch Multi-Layer Design','Cooling Gel Memory Foam','Zero Motion Transfer','CertiPUR-US Certified','Breathable Cover','10-Year Warranty'],
    specs:{'Height':'12 inches','Layers':'5','Firmness':'Medium-Firm','Warranty':'10 years','Cover':'Removable & Washable'},
    colors:[],sizes:['Single','Double','Queen','King'],inStock:true,stockCount:23,seller:'HomeLux Living',deliveryDays:5,freeDelivery:true,tags:['mattress','bedroom','sleep','comfort']},
  {id:17,name:'Smart RGB LED Desk Lamp',slug:'smart-lamp',category:'home',brand:'HomeLux',
    price:3999,originalPrice:5499,discount:27,rating:4.4,reviewCount:5678,
    image:'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop'],
    description:'16M color RGB LED lamp with wireless charging base, touch controls, and app integration.',
    features:['16M RGB Colors','Wireless Charging Base','Touch Controls','App & Voice Control','5 Brightness Levels','Eye-Care Technology'],
    specs:{'Colors':'16 Million RGB','Lumens':'800lm','Power':'15W','Charging':'15W Qi','Control':'Touch + App'},
    colors:['#f8fafc','#1a1a2e'],inStock:true,stockCount:167,seller:'HomeLux Living',deliveryDays:2,freeDelivery:true,tags:['lamp','lighting','smart home','desk']},

  // BOOKS
  {id:18,name:'The Art of Programming',slug:'art-of-programming',category:'books',brand:'BookWorm',
    price:599,originalPrice:899,discount:33,rating:4.9,reviewCount:12456,
    image:'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=600&fit=crop'],
    description:'The definitive guide to writing elegant, efficient code. Covers algorithms, design patterns, and best practices.',
    features:['600+ Pages','Code Examples in 5 Languages','Algorithm Visualizations','Practice Problems','Online Resources Access','Hardcover Edition'],
    specs:{'Pages':'648','Publisher':'TechPress','Language':'English','Format':'Hardcover','ISBN':'978-0-13-468599-1'},
    colors:[],inStock:true,stockCount:890,seller:'BookWorm Publishing',deliveryDays:2,freeDelivery:true,tags:['book','programming','coding','education']},
  {id:19,name:'AI Revolution: Future of Intelligence',slug:'ai-revolution',category:'books',brand:'BookWorm',
    price:799,originalPrice:1099,discount:27,rating:4.7,reviewCount:8765,
    image:'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop'],
    description:'Explore how artificial intelligence is reshaping our world — from healthcare to creative arts.',
    features:['400+ Pages','Case Studies','Expert Interviews','Future Predictions','Illustrated','Audiobook Code Included'],
    specs:{'Pages':'432','Publisher':'FuturePub','Language':'English','Format':'Paperback'},
    colors:[],inStock:true,stockCount:567,seller:'BookWorm Publishing',deliveryDays:2,freeDelivery:true,tags:['book','ai','technology','future']},
  {id:20,name:'Mindful Living: A Modern Guide',slug:'mindful-living',category:'books',brand:'BookWorm',
    price:449,originalPrice:699,discount:36,rating:4.5,reviewCount:5432,
    image:'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop'],
    description:'Transform your daily life with practical mindfulness techniques backed by neuroscience research.',
    features:['300+ Pages','Guided Exercises','Scientific References','Daily Practice Plans','Meditation Scripts','Journal Prompts'],
    specs:{'Pages':'324','Publisher':'WellPress','Language':'English','Format':'Paperback'},
    colors:[],inStock:true,stockCount:345,seller:'BookWorm Publishing',deliveryDays:2,freeDelivery:true,tags:['book','mindfulness','wellness','selfhelp']},
  {id:21,name:'Startup Playbook: Zero to IPO',slug:'startup-playbook',category:'books',brand:'BookWorm',
    price:699,originalPrice:999,discount:30,rating:4.6,reviewCount:6789,
    image:'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&h=600&fit=crop'],
    description:'The complete guide to building, scaling, and exiting a startup. Written by serial entrepreneurs.',
    features:['500+ Pages','Real Case Studies','Financial Templates','Pitch Deck Frameworks','Networking Strategies','Online Community Access'],
    specs:{'Pages':'512','Publisher':'BizPress','Language':'English','Format':'Hardcover'},
    colors:[],inStock:true,stockCount:234,seller:'BookWorm Publishing',deliveryDays:2,freeDelivery:true,tags:['book','startup','business','entrepreneur']},

  // SPORTS
  {id:22,name:'Professional Cork Yoga Mat',slug:'yoga-mat',category:'sports',brand:'FitPro',
    price:1999,originalPrice:2999,discount:33,rating:4.5,reviewCount:4321,
    image:'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop'],
    description:'Eco-friendly natural cork yoga mat with superior grip, cushioning, and antimicrobial surface.',
    features:['Natural Cork Surface','6mm Thick Cushioning','Non-Slip TPE Base','Antimicrobial','Eco-Friendly Materials','Carry Strap Included'],
    specs:{'Material':'Cork + TPE','Thickness':'6mm','Size':'183x61cm','Weight':'2.5kg'},
    colors:[],inStock:true,stockCount:234,seller:'FitPro Sports',deliveryDays:2,freeDelivery:true,tags:['yoga','fitness','mat','exercise']},
  {id:23,name:'Smart Fitness Tracker Band',slug:'fitness-band',category:'sports',brand:'FitPro',
    price:4999,originalPrice:6999,discount:29,rating:4.4,reviewCount:7654,
    image:'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop'],
    description:'Advanced fitness tracker with heart rate, SpO2, sleep tracking, and 14-day battery life.',
    features:['Heart Rate & SpO2 Monitor','14-Day Battery Life','1.47" AMOLED Display','50m Water Resistant','110+ Sport Modes','Sleep & Stress Tracking'],
    specs:{'Display':'1.47" AMOLED','Battery':'14 days','Sensors':'HR, SpO2','Water':'50m','Weight':'26g'},
    colors:['#1a1a2e','#06b6d4','#ec4899'],inStock:true,stockCount:345,seller:'FitPro Sports',deliveryDays:2,freeDelivery:true,tags:['fitness','tracker','health','wearable']},
  {id:24,name:'Mountain Bicycle Pro 29"',slug:'mountain-bicycle',category:'sports',brand:'FitPro',
    price:18999,originalPrice:27999,discount:32,rating:4.7,reviewCount:1234,
    image:'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&h=600&fit=crop'],
    description:'Full suspension mountain bike with carbon frame, hydraulic disc brakes, and 29" tubeless wheels.',
    features:['Carbon Fiber Frame','Full Suspension 150mm','Hydraulic Disc Brakes','29" Tubeless Wheels','Shimano 12-Speed','Dropper Seatpost'],
    specs:{'Frame':'Carbon Fiber','Wheels':'29"','Gears':'Shimano 12-Speed','Brakes':'Hydraulic Disc','Suspension':'Full 150mm','Weight':'12.5kg'},
    colors:['#1a1a2e','#ef4444','#06b6d4'],inStock:true,stockCount:23,seller:'FitPro Sports',deliveryDays:5,freeDelivery:true,tags:['bicycle','mountain','outdoor','sport']},
  {id:25,name:'4-Person Camping Tent Ultra',slug:'camping-tent',category:'sports',brand:'FitPro',
    price:7999,originalPrice:11999,discount:33,rating:4.5,reviewCount:2345,
    image:'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop'],
    description:'Ultra-light 4-person tent with 5000mm waterproof rating, UV protection, and instant pop-up setup.',
    features:['4-Person Capacity','5000mm Waterproof','UV50+ Protection','Instant Pop-Up Setup','Aluminum Poles','2 Doors & 2 Vestibules'],
    specs:{'Capacity':'4 Person','Waterproof':'5000mm','Weight':'3.2kg','Setup':'Pop-Up','Poles':'Aluminum','Seasons':'3-Season'},
    colors:['#10b981','#f59e0b','#94a3b8'],inStock:true,stockCount:56,seller:'FitPro Sports',deliveryDays:3,freeDelivery:true,tags:['tent','camping','outdoor','adventure']},

  // BEAUTY
  {id:26,name:'Luxury 10-Step Skincare Set',slug:'skincare-set',category:'beauty',brand:'BeautyGlow',
    price:3999,originalPrice:6999,discount:43,rating:4.6,reviewCount:5432,
    image:'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop'],
    description:'Complete Korean-inspired 10-step skincare routine with hyaluronic acid, vitamin C, and retinol.',
    features:['10 Full-Size Products','Hyaluronic Acid Serum','Vitamin C Brightening','Retinol Night Cream','SPF 50 Sunscreen','Cruelty-Free & Vegan'],
    specs:{'Products':'10','Skin Type':'All Types','Key Ingredients':'HA, Vitamin C, Retinol','Cruelty Free':'Yes'},
    colors:[],inStock:true,stockCount:89,seller:'BeautyGlow Store',deliveryDays:3,freeDelivery:true,tags:['skincare','beauty','korean','routine']},
  {id:27,name:'Professional Ionic Hair Dryer',slug:'hair-dryer',category:'beauty',brand:'BeautyGlow',
    price:5999,originalPrice:8999,discount:33,rating:4.5,reviewCount:3456,
    image:'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&h=600&fit=crop'],
    description:'Salon-quality ionic hair dryer with 110,000 RPM motor, negative ion technology, and magnetic attachments.',
    features:['110,000 RPM Motor','Negative Ion Technology','4 Heat Settings','Magnetic Attachments','Lightweight 380g','Professional Diffuser'],
    specs:{'Motor':'110K RPM','Power':'1600W','Weight':'380g','Cord':'2.7m','Settings':'4 Heat + 3 Speed'},
    colors:['#ec4899','#1a1a2e','#f8fafc'],inStock:true,stockCount:123,seller:'BeautyGlow Store',deliveryDays:2,freeDelivery:true,tags:['hair dryer','beauty','salon','professional']},
  {id:28,name:'Artisan Perfume Collection',slug:'perfume-collection',category:'beauty',brand:'BeautyGlow',
    price:2999,originalPrice:4999,discount:40,rating:4.7,reviewCount:2789,
    image:'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=600&fit=crop'],
    description:'Luxury perfume discovery set with 5 artisan fragrances crafted by master perfumers from Grasse, France.',
    features:['5 Artisan Fragrances','Eau de Parfum','Travel-Size 15ml Each','Gift Box Packaging','Fragrance Guide Included','Crafted in France'],
    specs:{'Volume':'5 x 15ml','Type':'Eau de Parfum','Origin':'Grasse, France','Longevity':'8-12 hours'},
    colors:[],inStock:true,stockCount:67,seller:'BeautyGlow Store',deliveryDays:3,freeDelivery:true,tags:['perfume','fragrance','luxury','gift']},

  // TOYS
  {id:29,name:'STEM Robot Building Kit',slug:'robot-kit',category:'toys',brand:'PlayZone',
    price:4999,originalPrice:7499,discount:33,rating:4.8,reviewCount:3456,
    image:'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600&h=600&fit=crop'],
    description:'Build and code 5 different robots with this STEM kit. Features Bluetooth control and visual programming.',
    features:['5 Robot Designs','400+ Pieces','Bluetooth App Control','Visual Programming','Compatible with Scratch','Ages 8-16'],
    specs:{'Pieces':'400+','Robots':'5 Designs','Control':'Bluetooth App','Programming':'Visual/Scratch','Ages':'8-16'},
    colors:[],inStock:true,stockCount:78,seller:'PlayZone Toys',deliveryDays:3,freeDelivery:true,tags:['robot','stem','coding','educational','kids']},
  {id:30,name:'4K Camera Drone Explorer',slug:'camera-drone',category:'toys',brand:'TechVista',
    price:8999,originalPrice:12999,discount:31,rating:4.5,reviewCount:2345,
    image:'https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=600&h=600&fit=crop'],
    description:'Foldable 4K drone with gimbal stabilization, obstacle avoidance, and 40-minute flight time.',
    features:['4K 60fps Camera','3-Axis Gimbal','Obstacle Avoidance','40-Min Flight Time','5km Range','Foldable Design'],
    specs:{'Camera':'4K 60fps','Gimbal':'3-Axis','Flight Time':'40 min','Range':'5km','Weight':'249g'},
    colors:['#6b7280'],inStock:true,stockCount:45,seller:'TechVista Store',deliveryDays:3,freeDelivery:true,tags:['drone','camera','flying','gadget']},
  {id:31,name:'Complete Board Games Collection',slug:'board-games',category:'toys',brand:'PlayZone',
    price:2499,originalPrice:3999,discount:38,rating:4.4,reviewCount:4567,
    image:'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&h=600&fit=crop'],
    description:'Premium collection of 12 classic and strategy board games in a beautiful wooden chest.',
    features:['12 Board Games','Premium Wooden Chest','High-Quality Pieces','Strategy & Classic Mix','2-8 Players','Family Friendly'],
    specs:{'Games':'12','Players':'2-8','Material':'Wood + Premium Cards','Ages':'6+'},
    colors:[],inStock:true,stockCount:89,seller:'PlayZone Toys',deliveryDays:3,freeDelivery:true,tags:['board games','family','strategy','entertainment']},

  // GROCERIES
  {id:32,name:'Organic Japanese Green Tea Set',slug:'green-tea-set',category:'grocery',brand:'GreenLeaf',
    price:1299,originalPrice:1999,discount:35,rating:4.6,reviewCount:5678,
    image:'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=600&fit=crop'],
    description:'Premium matcha and sencha collection sourced from Kyoto. Includes ceremonial-grade matcha and 4 loose-leaf varieties.',
    features:['Ceremonial Grade Matcha','4 Loose-Leaf Varieties','Sourced from Kyoto','Organic Certified','Bamboo Whisk Included','100g Total'],
    specs:{'Origin':'Kyoto, Japan','Weight':'100g Total','Varieties':'5','Organic':'Yes'},
    colors:[],inStock:true,stockCount:234,seller:'GreenLeaf Organics',deliveryDays:2,freeDelivery:false,tags:['tea','organic','japanese','matcha']},
  {id:33,name:'Premium Mixed Dry Fruits Box',slug:'dry-fruits-box',category:'grocery',brand:'GreenLeaf',
    price:2499,originalPrice:3499,discount:29,rating:4.7,reviewCount:4321,
    image:'https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=600&h=600&fit=crop'],
    description:'Handpicked selection of premium almonds, cashews, pistachios, walnuts, dates, and figs in a gift box.',
    features:['6 Premium Varieties','500g Assortment','Hand-Sorted Grade A','Gift Box Packaging','No Preservatives','Rich in Nutrients'],
    specs:{'Weight':'500g','Varieties':'6','Grade':'Premium A','Preservatives':'None'},
    colors:[],inStock:true,stockCount:156,seller:'GreenLeaf Organics',deliveryDays:2,freeDelivery:true,tags:['dry fruits','nuts','healthy','gift']},
  {id:34,name:'Belgian Chocolate Gift Collection',slug:'chocolate-collection',category:'grocery',brand:'GreenLeaf',
    price:1999,originalPrice:2999,discount:33,rating:4.8,reviewCount:6789,
    image:'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&h=600&fit=crop'],
    description:'Artisan Belgian chocolates in 12 exquisite flavors, handcrafted by master chocolatiers in Brussels.',
    features:['12 Unique Flavors','Belgian Cocoa','Handcrafted','Premium Gift Box','24 Pieces','No Artificial Flavors'],
    specs:{'Pieces':'24','Flavors':'12','Origin':'Brussels, Belgium','Weight':'300g'},
    colors:[],inStock:true,stockCount:89,seller:'GreenLeaf Organics',deliveryDays:3,freeDelivery:true,tags:['chocolate','belgian','gift','gourmet']},

  // HEALTH
  {id:35,name:'Plant-Based Protein Powder',slug:'protein-powder',category:'health',brand:'FitPro',
    price:2999,originalPrice:3999,discount:25,rating:4.5,reviewCount:8765,
    image:'https://images.unsplash.com/photo-1593095948071-474c5cc2c1cf?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1593095948071-474c5cc2c1cf?w=600&h=600&fit=crop'],
    description:'Premium plant-based protein blend with 30g protein per serving, digestive enzymes, and zero sugar.',
    features:['30g Protein/Serving','Plant-Based Blend','Zero Sugar','Digestive Enzymes','30 Servings','6 Flavors Available'],
    specs:{'Protein':'30g/serving','Servings':'30','Sugar':'0g','Source':'Pea + Rice + Hemp','Weight':'1kg'},
    colors:[],inStock:true,stockCount:345,seller:'FitPro Sports',deliveryDays:2,freeDelivery:true,tags:['protein','fitness','supplement','vegan']},
  {id:36,name:'Percussion Massage Gun Pro',slug:'massage-gun',category:'health',brand:'FitPro',
    price:7999,originalPrice:11999,discount:33,rating:4.6,reviewCount:3456,
    image:'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=600&h=600&fit=crop'],
    description:'Professional percussion therapy device with 30 speed levels, 8 heads, and ultra-quiet brushless motor.',
    features:['30 Speed Levels','8 Massage Heads','Brushless Motor','6-Hour Battery','Ultra-Quiet 35dB','Carrying Case'],
    specs:{'Speeds':'30 Levels','Heads':'8','Battery':'6 hours','Noise':'35dB','Stroke':'16mm','Stall Force':'60lbs'},
    colors:['#1a1a2e','#6b7280','#ef4444'],inStock:true,stockCount:123,seller:'FitPro Sports',deliveryDays:2,freeDelivery:true,tags:['massage','recovery','fitness','therapy']},
  {id:37,name:'Smart Blood Pressure Monitor',slug:'bp-monitor',category:'health',brand:'Arknetch',
    price:3499,originalPrice:4999,discount:30,rating:4.4,reviewCount:2345,
    image:'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=600&h=600&fit=crop'],
    description:'FDA-cleared smart blood pressure monitor with app tracking, irregular heartbeat detection, and family profiles.',
    features:['FDA Cleared','App Health Tracking','Irregular Heartbeat Detection','2-User Profiles','120 Memory Storage','Voice Broadcast'],
    specs:{'Accuracy':'±3 mmHg','Cuff':'22-42cm','Memory':'120 x 2 users','Connectivity':'Bluetooth','Power':'4x AAA'},
    colors:['#f8fafc'],inStock:true,stockCount:89,seller:'Arknetch Official',deliveryDays:2,freeDelivery:true,tags:['health','blood pressure','medical','monitor']},

  // AUTOMOTIVE
  {id:38,name:'Smart Dash Camera 4K',slug:'dash-camera',category:'automotive',brand:'AutoPrime',
    price:5999,originalPrice:8999,discount:33,rating:4.5,reviewCount:3456,
    image:'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&h=600&fit=crop'],
    description:'4K dual-channel dash cam with night vision, GPS logging, parking mode, and emergency recording.',
    features:['4K Front + 1080P Rear','Night Vision','GPS Logging','Parking Mode','Emergency Recording','Voice Control'],
    specs:{'Resolution':'4K + 1080P','FOV':'170° + 140°','Storage':'Up to 256GB','GPS':'Built-in','Display':'3" IPS'},
    colors:['#1a1a2e'],inStock:true,stockCount:78,seller:'AutoPrime Motors',deliveryDays:2,freeDelivery:true,tags:['dashcam','car','safety','automotive']},
  {id:39,name:'Portable Car Jump Starter',slug:'jump-starter',category:'automotive',brand:'AutoPrime',
    price:3999,originalPrice:5999,discount:33,rating:4.6,reviewCount:2345,
    image:'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop',
    images:['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop'],
    description:'Compact 2000A jump starter with 20000mAh power bank, LED flashlight, and tire inflator combo.',
    features:['2000A Peak Current','20000mAh Power Bank','Built-in Tire Inflator','LED Emergency Light','USB-C Fast Charge','Smart Clamps'],
    specs:{'Peak Current':'2000A','Capacity':'20000mAh','Engine':'Up to 8L Gas','Ports':'USB-C, USB-A, 12V','Weight':'800g'},
    colors:['#f59e0b','#1a1a2e'],inStock:true,stockCount:56,seller:'AutoPrime Motors',deliveryDays:2,freeDelivery:true,tags:['jump starter','car','emergency','power bank']}
];

// Deal/offer presets
const DEALS = [
  {id:1,productId:7,endsIn:7200,claimed:67,total:100,label:'Lightning Deal'},
  {id:2,productId:16,endsIn:14400,claimed:45,total:80,label:'Deal of the Day'},
  {id:3,productId:26,endsIn:3600,claimed:89,total:100,label:'Lightning Deal'},
  {id:4,productId:9,endsIn:10800,claimed:34,total:60,label:'Limited Time'},
  {id:5,productId:30,endsIn:5400,claimed:56,total:75,label:'Flash Sale'},
  {id:6,productId:4,endsIn:18000,claimed:23,total:50,label:'Deal of the Day'},
  {id:7,productId:15,endsIn:9000,claimed:78,total:100,label:'Lightning Deal'},
  {id:8,productId:34,endsIn:12000,claimed:45,total:60,label:'Limited Time'}
];

const COUPONS = [
  {code:'WELCOME10',discount:10,type:'percent',minOrder:500,maxDiscount:1000,description:'10% off on first order'},
  {code:'ARKNETCH500',discount:500,type:'flat',minOrder:3000,maxDiscount:500,description:'₹500 off on orders above ₹3000'},
  {code:'FESTIVE20',discount:20,type:'percent',minOrder:2000,maxDiscount:5000,description:'20% off during festival sale'},
  {code:'FREESHIPPER',discount:0,type:'shipping',minOrder:0,maxDiscount:0,description:'Free shipping on any order'}
];

const BANNERS = [
  {title:'Arknetch Grand Sale',subtitle:'Up to 70% off on Electronics',cta:'Shop Now',gradient:'linear-gradient(135deg,#7c3aed,#06b6d4)',category:'electronics'},
  {title:'Fashion Week Special',subtitle:'New Arrivals + Extra 20% Off',cta:'Explore',gradient:'linear-gradient(135deg,#ec4899,#f59e0b)',category:'fashion'},
  {title:'Home Makeover Sale',subtitle:'Smart Home Essentials from ₹3,999',cta:'Browse',gradient:'linear-gradient(135deg,#10b981,#06b6d4)',category:'home'},
  {title:'Fitness February',subtitle:'Gear up with FitPro — up to 40% off',cta:'Shop Fitness',gradient:'linear-gradient(135deg,#f59e0b,#ef4444)',category:'sports'}
];

// Sample reviews
const SAMPLE_REVIEWS = [
  {userName:'Rahul S.',rating:5,title:'Absolutely amazing!',comment:'Best purchase I have made this year. Quality is outstanding and delivery was super fast.',date:'2026-03-15',helpful:42},
  {userName:'Priya M.',rating:4,title:'Great value for money',comment:'Really impressed with the build quality. Minor packaging issue but product is perfect.',date:'2026-03-10',helpful:28},
  {userName:'Amit K.',rating:5,title:'Exceeded expectations',comment:'Was skeptical at first but this product truly delivers on all its promises. Highly recommended!',date:'2026-02-28',helpful:35},
  {userName:'Sneha R.',rating:4,title:'Very good product',comment:'Using it daily and very satisfied. The features work exactly as described.',date:'2026-02-20',helpful:19},
  {userName:'Vikram P.',rating:3,title:'Decent but could be better',comment:'Good overall but I expected a bit more at this price point. Still, no major complaints.',date:'2026-02-15',helpful:12}
];

// Frequently bought together bundles
const BUNDLES = [
  {products:[1,3,5],discount:15},
  {products:[2,3,17],discount:12},
  {products:[7,10,11],discount:18},
  {products:[22,23,35],discount:15},
  {products:[26,27,28],discount:20}
];

// Helper functions
function getProduct(id){return PRODUCTS.find(p=>p.id===id)}
function getProductsByCategory(cat){return PRODUCTS.filter(p=>p.category===cat)}
function searchProducts(query){
  const q=query.toLowerCase();
  return PRODUCTS.filter(p=>p.name.toLowerCase().includes(q)||p.category.includes(q)||p.brand.toLowerCase().includes(q)||p.tags.some(t=>t.includes(q))||p.description.toLowerCase().includes(q));
}
function formatPrice(p){return '₹'+p.toLocaleString('en-IN')}
function getStarsHTML(rating){
  let s='';const full=Math.floor(rating),half=rating%1>=0.5;
  for(let i=0;i<full;i++)s+='★';
  if(half)s+='★';
  for(let i=0;i<5-full-(half?1:0);i++)s+='☆';
  return s;
}
function getRandomProducts(count,excludeId){
  const filtered=PRODUCTS.filter(p=>p.id!==excludeId);
  const shuffled=[...filtered].sort(()=>Math.random()-0.5);
  return shuffled.slice(0,count);
}
function getRelatedProducts(product,count=4){
  return PRODUCTS.filter(p=>p.id!==product.id&&p.category===product.category).slice(0,count);
}
